server:
  port: '5050'

file:
  userProfile-upload-dir: upload/images/profile/  # 운영 환경 파일 경로
  userProfile-url-prefix: http://13.209.114.27:5050/api/userProfile/images/
  review-upload-dir: upload/images/review/
  review-url-prefix: http://13.209.114.27:5050/reviews/images/

spring:
  application:
    name: TripSupporter
  datasource:
    # 서버에 확인할 때 사용
#    url: jdbc:mysql://database-trip.cvm0eac28eqd.ap-northeast-2.rds.amazonaws.com:3306/tripdb
#    username: admin
#    password: trip970708!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#     로컬에서 테스트 할 때 사용
     url: jdbc:mysql://localhost:3306/testdb
     username: root
     password: 1234
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: handtrip2024@gmail.com
    password: ondspowvlzzjayst
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: db1a00d00b321eaf4862130c075480e2
            #            client-secret: g8UFiKlUaSHdhubQVLoatcaAcw9B9jSJ
            authorization-grant-type: authorization_code
            redirect-uri: http://13.209.114.27:5050/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          google:
            scope:
              - profile
              - email
            client-id: 621024947372-pphaarojd2nbej6bvjj0va6nt5hu85gn.apps.googleusercontent.com
            client-secret: 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
          naver:
            client-name: Naver
            scope:
              - name
              - email
              - profile_image
            authorization-grant-type: authorization_code
            client-id: Z1VGivmPwNqFyLhvBddw
            client-secret: hxUJQ3fS2G
            redirect-uri: http://localhost:5050/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    redis:
      port: 6379
      host: 13.209.114.27

jwt:
  secret: 6lwIEEF7Hqg0PCO6KxHoGe6kVqPRdgvnmQp3KiN0RTj4E3dAfqQ2Yi4Ttr9MxlZT
  access:
    expiration: 18000000
  refresh:
    expiration: 36000000




  servlet:
    multipart:
      # 최대 파일 크기
      max-file-size: 5MB
      # 최대 요청 크기 (여러 파일 업로드 시)
      max-request-size: 5MB
      # 임시 파일을 저장할 경로
      location: /tmp/uploads


#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security.oauth2: DEBUG
